### ISSUE TITLE
Enforce pr title conventions

### ISSUE THREAD

**Issue by dimabru** [allero-io/allero#105]
**Is your feature request related to a problem? Please describe.**
PR titles should align to the same standards

**Describe the solution you'd like**
A Github workflow that runs on every PR that enforces commit message conventions as described [here](https://gist.github.com/brianclements/841ea7bffdb01346392c) 
For example: 
`build: support docker push`
`refactor: improve unit tests`
`feat: create json output flag`

workflow should do the follwing:
1. enforce all in lowercase
2. make sure valid prefix exists (build, feat, bug, etc.)

**Comment by dolby360** [comment]
Actually not just the PR name this is a [conventional commit ](https://www.conventionalcommits.org/en/v1.0.0/) message. I want to promote a [project](https://github.com/TomerFi/auto-me-bot) by @tomerFi, to which I am also one of the contributors. I think this is a great tool that does exactly what we need here.

**Comment by dolby360** [comment]
I can do this task if you want

**Comment by TomerFi** [comment]
@dolby360 I think we can can either add a flag inside the _conventional-commits-handler_ to include PR titles:

```yaml
---
pr:
  conventionalCommits:
    includePrTitle: true
    rules:
      'body-max-line-length': [2, 'always', 150]
```

or add a designated handler:

```yaml
---
pr:
  conventionalPrTitles:
  conventionalCommits:
    rules:
      'body-max-line-length': [2, 'always', 150]
```

I'm not sure what's better...
WDYT?
