### ISSUE TITLE
[New Rule] Prevent usage of plain text password

### ISSUE THREAD

**Issue by idanshahar** [allero-io/allero#17]
Many actions need a username and password.

Prevent usage of password that are not stored in github secrets.

Docker Login:
```
   name: Login to JFrog 🐸  
        uses: docker/login-action@v1
        with:
          registry: <your artifactory>.jfrog.io
          username: ${{ secrets.JFROG_USER_WRITER }}
          password: **this_is_my_password**
```

SonarQube:

```
  sonarQubeTrigger:
    name: SonarQube Trigger
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: SonarQube Scan
      uses: kitabisa/sonarqube-action@master
      with:
        host: ${{ secrets.SONARQUBE_HOST }}
        login: **this_is_my_password**

```

UploadBinary

```
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Upload deb package to Bintray
      uses: bpicode/github-action-upload-bintray@master
      with:
        file: ./path/to/example-package_1.0_amd64.deb
        api_user: example-user
        api_key: **this_is_my_api_key**

```
