### ISSUE TITLE
[New Rule] Prevent usage of node without specifying a version

### ISSUE THREAD

**Issue by OriYosef** [allero-io/allero#20]
The `node-version` input is optional. If not supplied, the node version from PATH will be used. However, it is recommended to always specify Node.js version and don't rely on the system one.

Bad practice:
```
steps:
- uses: actions/setup-node@v3
- run: npm ci
- run: npm test
```

Recommended usage:
```
steps:
- uses: actions/setup-node@v3
  with:
    node-version: 16
- run: npm ci
- run: npm test
```
