### ISSUE TITLE
[New Rule] Prevent usage of python without specifying a version

### ISSUE THREAD

**Issue by OriYosef** [allero-io/allero#21]
It is recommended to specify a python version to prevent potential breaking changes due to patch updates. 
You should specify the exact major and minor versions. patch version is optional.

Bad practice:
```
steps:
- uses: actions/setup-python@v4
- run: python my_script.py
```

Recommended usage:
```
steps:
- uses: actions/setup-python@v4
  with:
    python-version: '3.7.5' 
- run: python my_script.py
```
